services:
  - type: web
    name: 911bot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: FLASK_ENV
        value: production
